[package]
name = "mic-rec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14.1"
crossbeam-channel = "0.5.6"
dasp = "0.11.0"
thiserror = "1.0.37"
tracing = "0.1.37"
