name: Build and Test

on:
  push:
    branches:
      - rework

  pull_request:
    branches:
      - rework

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: 'rustfmt, clippy'

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ./

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        uses: giraffate/clippy-action@v1
        with:
          #reporter: 'github-pr-review'
          reporter: 'github-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          clippy_flags: --all-targets --all-features
        working-directory: ./

  rust:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ./

      - name: Compile Tests
        run: cargo test --no-run --all-features
        working-directory: ./

      - name: Test
        run: cargo test --all-features
