name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  NATIVE_DEPS: libasound2-dev libarchive-tools

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: 'rustfmt, clippy'

      - uses: Swatinem/rust-cache@v2

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Install apt packages
        run: sudo apt install ${{ env.NATIVE_DEPS }}

      - name: Run clippy
        uses: giraffate/clippy-action@v1
        with:
          #reporter: 'github-pr-review'
          reporter: 'github-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

  rust:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        run: cargo install --debug cargo-make

      - name: Install apt packages
        run: sudo apt install ${{ env.NATIVE_DEPS }}

      - name: Compile Tests
        run: cargo make test-compile

      - name: Test
        run: cargo make test
